### ISSUE TITLE
Ajouter une licence

### ISSUE THREAD

**Issue by maukoquiroga** [sgmap/plante-et-moi-backend#1]
Ce depot n'a pas encore une [licence](https://github.com/sgmap/beta.gouv.fr/wiki/Publier#licence), pensez à en ajouter une.

**Comment by jdauphant** [comment]
Je propose une MIT pour celui là #2 .
On pousse notre objectif qui est des promouvoir la biodiversité en ville.
Cette outil pourrait disparaître ou être absorbé si besoin, ce n'est pas le coeur de métier.
